FROM rust:latest

# install system dependencies

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install -y gcc-aarch64-linux-gnu pkg-config libudev-dev:arm64 \
    && rm -rf /var/lib/apt/lists/*

# add aarch64 target

RUN rustup target add aarch64-unknown-linux-gnu

# set environment variables for cross compilation

ENV PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
ENV PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig
ENV PKG_CONFIG_SYSROOT_DIR=/

# cache dependencies

COPY Cargo.toml Cargo.toml
RUN mkdir -p src
RUN echo "fn main() {}" > src/main.rs
RUN cargo build --release --target=aarch64-unknown-linux-gnu

# copy source code

RUN rm -rf src
COPY Cargo.toml Cargo.toml
COPY src ./src

# build

RUN cargo build --release --target=aarch64-unknown-linux-gnu

# prepare output

RUN mkdir -p /output
RUN cp target/aarch64-unknown-linux-gnu/release/os ./os

# on run, copy the built binary to output directory

CMD ["cp", "os", "/output/os"]
