set dotenv-load := true

deploy:
    @echo 'Build and deploy on Pi'
    docker buildx build --platform=linux/arm64 --progress=plain -t thermo-os . && docker run --rm -v "$(pwd)/build:/output" thermo-os
    ssh "$PI_USER@$PI_IP" "rm /home/$PI_USER/os || true"
    scp .env "$PI_USER@$PI_IP:/home/$PI_USER/"
    scp build/os "$PI_USER@$PI_IP:/home/$PI_USER/os"

run-remote:
    @echo 'Build, deploy and run on Pi'
    just deploy
    scp .env "$PI_USER@$PI_IP:/home/$PI_USER/"
    ssh "$PI_USER@$PI_IP" 'RUST_LOG=warn,os=trace ./os'
